apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: cassandra-lab
  labels:
    app: grafana-cassandra-lab
spec:
  type: LoadBalancer # ClusterIP
  selector:
    app: grafana-cassandra-lab
  ports:
    - name: grfn
      port: 3000
      targetPort: 3000
      nodePort: 30000