apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jmx-exporter-pvc
  namespace: cassandra-lab
spec:
  accessModes:
    - ReadOnlyMany  
  resources:
    requests:
      storage: 8.5Mi
  volumeName: jmx-exporter-pv