apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-jmx-configmap
  labels: 
    app: prometheus-jmx
  namespace: cassandra-lab
data:
  prometheus.yml: |
    
    # my global config
    global:
      scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
      # scrape_timeout is set to the global default (10s).


    # A scrape configuration containing exactly one endpoint to scrape:
    # Here it's Prometheus itself.
    scrape_configs:
      # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
      - job_name: "cassandra"
        # metrics_path defaults to '/metrics'
        # scheme defaults to 'http'.
        static_configs:
          - targets: ["cassandra-0.cassandra.cassandra-lab.svc.cluster.local:7200"]
          - targets: ["cassandra-1.cassandra.cassandra-lab.svc.cluster.local:7200"]
          - targets: ["cassandra-2.cassandra.cassandra-lab.svc.cluster.local:7200"]