apiVersion: v1
kind: Service
metadata:
  name: prometheus-jmx
  namespace: cassandra-lab
  labels:
    app: prometheus-jmx
spec:
  type: LoadBalancer # ClusterIP
  selector:
    app: prometheus-jmx
  ports:
    - name: prom
      port: 9090
      targetPort: 9090
      nodePort: 30090