# Prometheus 1.2.0

startDelaySeconds: 0
#jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:5555/jmxrmi
#jmxUrl: service:jmx:rmi:///jndi/rmi://cassandra-lab:7199/jmxrmi
hostPort: "cassandra:7199"
#hostPort: 127.0.0.1:7199
username: ""
password: ""
ssl: false
rules:
  - pattern: ".*"

  # Testing transform Array String to number for enable scrape metric
  #- pattern: 'org.apache.cassandra.db<type=StorageService><>Tokens'
    #value: 'len:Tokens'
    #value: ${#Tokens}
    #  value: "{{value.length}}"
    #type: UNTYPED
    #  type: GAUGE

# Options of jmx_exporter

#host: localhost:7199
#ssl: False
#user:
#password:
##listenAddress: 0.0.0.0
##listenPort: 7070
##listenPort: 8080
## Regular expression to match environment variables that will be added
## as labels to all data points. The name of the label will be either
## $1 from the regex below, or the entire environment variable name if no match groups are defined
##
## Example:
## additionalLabelsFromEnvvars: "^ADDL\_(.*)$"
#additionalLabelsFromEnvvars:
#blacklist:
#   # Unaccessible metrics (not enough privilege)
#   - java:lang:memorypool:.*usagethreshold.*
#
#   # Leaf attributes not interesting for us but that are presents in many path (reduce cardinality of metrics)
#   - .*:999thpercentile
#   - .*:95thpercentile
#   - .*:fifteenminuterate
#   - .*:fiveminuterate
#   - .*:durationunit
#   - .*:rateunit
#   - .*:stddev
#   - .*:meanrate
#   - .*:mean
#   - .*:min
#
#   # Path present in many metrics but uninterresting
#   - .*:viewlockacquiretime:.*
#   - .*:viewreadtime:.*
#   - .*:cas[a-z]+latency:.*
#   - .*:colupdatetimedeltahistogram:.*
#
#   # Mostly for RPC, do not scrap them
#   - org:apache:cassandra:db:.*
#
#   # columnfamily is an alias for Table metrics in cassandra 3.x
#   # https://github.com/apache/cassandra/blob/8b3a60b9a7dbefeecc06bace617279612ec7092d/src/java/org/apache/cassandra/metrics/TableMetrics.java#L162
#   - org:apache:cassandra:metrics:columnfamily:.*
#
#   # Should we export metrics for system keyspaces/tables ?
#   - org:apache:cassandra:metrics:[^:]+:system[^:]*:.*
#
#   # Don't scrape us
#   - com:criteo:nosql:cassandra:exporter:.*
#
#maxScrapFrequencyInSec:
#  50:
#    - .*
#
#  # Refresh those metrics only every hour as it is costly for cassandra to retrieve them
#  3600:
#    - .*:snapshotssize:.*
#    - .*:estimated.*
#    - .*:totaldiskspaceused:.*