{
 "title": "Cassandra metrics",
 "description": "Dashboard lab to monitorize state of Cassandra cluster",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(org_apache_cassandra_db_StorageService_Joined,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "State nodes on ring",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "org_apache_cassandra_db_StorageService_Joined{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Resources used",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Memory used",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "java_lang_Memory_HeapMemoryUsage_used{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU - Load Average",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 13, "x": 0, "y": 99 },
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_SystemLoadAverage{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU - Cores Used",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 10, "x": 13, "y": 99 },
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_SystemCpuLoad{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DB space, RW Latency & \"Compaction\" process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Disk space used",
     "type": "stat",
     "description": "Total Disk space used by instance",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "org_apache_cassandra_metrics_Table_Value{instance=~\"$instance\", name=\"TotalDiskSpaceUsed\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total read latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by(instance) (org_apache_cassandra_metrics_Table_StdDev{instance=~\"$instance\", name=\"ReadLatency\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Write latency",
     "type": "timeseries",
     "description": "Write latency in ms",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by(instance) (org_apache_cassandra_metrics_Table_StdDev{instance=~\"$instance\", name=\"WriteLatency\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "\"Compaction\" pending tasks",
     "type": "timeseries",
     "description": "The \"Compaction\" is a process that merge SSTable files to delete duplicate data or old data.\n\nThis metric shows pending tasks.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "org_apache_cassandra_metrics_Compaction_Value{instance=~\"$instance\", name=\"PendingTasks\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Bytes compacted",
     "type": "barchart",
     "description": "Compaction is a process that merge SSTable files to delete duplicate data or old data.\n\nThis metric shows total bytes that had be compacted",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(org_apache_cassandra_metrics_Compaction_Count{instance=~\"$instance\", name=\"BytesCompacted\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "\"Hints\" and \"Reparations\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total \"Hints\"",
     "type": "timeseries",
     "description": "The hints is a pending write, is a note to write data latter.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "org_apache_cassandra_metrics_Storage_Count{instance=~\"$instance\", name=\"TotalHints\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Hints in progress",
     "type": "timeseries",
     "description": "The hints is a pending write, is a note to will write data later.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "targets": [
      {
       "expr": "org_apache_cassandra_metrics_Storage_Count{instance=~\"$instance\", name=\"TotalHintsInProgress\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Bytes pending to repair",
     "type": "timeseries",
     "description": "The reparations are the synchronization process of nodes. The next metrics shows total of bytes that should be repair.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(instance) (org_apache_cassandra_metrics_Table_Value{name=~\"BytesUnrepaired\", instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages Latency",
     "type": "timeseries",
     "description": "Messages betwen nodes of cluster",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "org_apache_cassandra_metrics_Messaging_StdDev{instance=~\"$instance\", name=\"datacenter1-Latency\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Messages dropped",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "sum by(instance) (org_apache_cassandra_metrics_DroppedMessage_MeanRate{instance=~\"$instance\", name=\"Dropped\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Messages timeout",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "org_apache_cassandra_net_MessagingService_TotalTimeouts{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "ThreadPools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Total active tasks",
   "type": "timeseries",
   "description": "Threadpools are multiple tasks by pool or by type tasks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(instance) (org_apache_cassandra_metrics_ThreadPools_Value{instance=~\"$instance\", name=\"ActiveTasks\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "timeseries",
   "description": "Multiple tasks by pool or by type tasks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by(instance) (org_apache_cassandra_metrics_ThreadPools_Value{instance=~\"$instance\", name=\"PendingTasks\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}