FROM otel/opentelemetry-collector-contrib:0.122.0
#FROM debian:12.8
#USER otel
#COPY ./dependencies.sh /tmp/dependencies.sh
#RUN ["bash", "-x", "/tmp/dependencies.sh"]
# false entrypoint:
#ENTRYPOINT ["tail", "-f", "/dev/null"]